In [1]:
from IPython.display import display
import torch

torch.set_printoptions(sci_mode=False)


In [2]:
A = torch.randn((8,3,5))

display(A.size())
display(A.size() == (8,3,5))

torch.Size([8, 3, 5])

True

In [3]:
display(A)
display(A[0][0])
display(A[0, :, 0])
display(A[0,0:])

tensor([[[    -1.2790,     -0.2711,      0.3548,     -2.6437,      0.6771],
         [    -0.6601,      0.9387,      0.3852,     -0.0009,     -2.7669],
         [     1.4789,     -0.9270,     -0.3607,     -0.3930,     -0.6742]],

        [[     1.0427,      1.3546,      0.5825,     -1.0135,     -0.8950],
         [    -0.5929,      0.0893,     -0.1758,     -1.6244,      0.7799],
         [     0.0257,     -0.0720,     -0.2373,      2.0032,      1.0474]],

        [[    -1.2152,     -0.3373,     -0.4093,     -1.6897,     -0.3156],
         [    -0.0111,     -0.4492,      0.0960,     -0.3800,      0.2292],
         [     0.7898,      0.6812,      0.1963,      2.8308,     -1.0212]],

        [[     0.8399,     -0.5190,     -0.1571,      0.5041,     -0.7950],
         [     0.1196,      0.6865,     -0.2720,     -1.4963,      0.4186],
         [     0.5699,     -0.8483,      0.5360,      1.2558,      0.5364]],

        [[     0.9572,      0.6480,      0.0583,     -0.7586,     -1.5818],
    

tensor([-1.2790, -0.2711,  0.3548, -2.6437,  0.6771])

tensor([-1.2790, -0.6601,  1.4789])

tensor([[    -1.2790,     -0.2711,      0.3548,     -2.6437,      0.6771],
        [    -0.6601,      0.9387,      0.3852,     -0.0009,     -2.7669],
        [     1.4789,     -0.9270,     -0.3607,     -0.3930,     -0.6742]])

In [4]:
C = torch.zeros((2, 3, 4))
display(C)
display(C.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

torch.float32

In [5]:
D = torch.randint(4, (2, 3, 4))
display(D)
display(D.dtype)

tensor([[[0, 0, 0, 3],
         [3, 2, 2, 0],
         [3, 2, 1, 3]],

        [[3, 0, 3, 3],
         [1, 1, 1, 0],
         [3, 1, 3, 0]]])

torch.int64

In [6]:
C + D

tensor([[[0., 0., 0., 3.],
         [3., 2., 2., 0.],
         [3., 2., 1., 3.]],

        [[3., 0., 3., 3.],
         [1., 1., 1., 0.],
         [3., 1., 3., 0.]]])

In [7]:
D.float()
C + D

tensor([[[0., 0., 0., 3.],
         [3., 2., 2., 0.],
         [3., 2., 1., 3.]],

        [[3., 0., 3., 3.],
         [1., 1., 1., 0.],
         [3., 1., 3., 0.]]])

In [8]:
torch.set_default_tensor_type('torch.FloatTensor')

In [9]:
C.device

device(type='cpu')

In [10]:
! nvidia-smi
torch.cuda.is_available()

Wed Aug  5 03:19:22 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

True