In [1]:
from IPython.display import display

import torch
from torch import nn

torch.set_printoptions(sci_mode=False)
torch.set_default_tensor_type('torch.FloatTensor')
device = torch.device('cuda' if torch.cuda.is_available else 'cpu')

In [2]:
linear = nn.Linear(in_features=4096, out_features=10) # Input dim = 1
conv2d = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=1) # Modifica los canales, no modifica las dimensiones de la imagen
relu = nn.ReLU(False) # False para no modificar el tensor original

In [3]:
x = torch.randn(4096)
y = linear(x)

display(x.shape)
display(y.shape)

display(x)
display(y)

torch.Size([4096])

torch.Size([10])

tensor([ 2.2424, -0.7976, -0.6836,  ..., -0.4183, -0.7582,  2.2917])

tensor([ 1.1516, -1.1645, -0.1090,  0.1100, -1.1523,  0.2585,  0.1026, -0.6961,
         0.1466, -0.6034], grad_fn=<AddBackward0>)

In [4]:
x = torch.randn((2, 3, 5, 7))
y = conv2d(x)
z = relu(x)

display(x.shape)
display(z.shape)
display(y.shape)

display(x)
display(z)
display(y)

torch.Size([2, 3, 5, 7])

torch.Size([2, 3, 5, 7])

torch.Size([2, 6, 5, 7])

tensor([[[[    -1.4675,     -0.5187,      0.4843,     -0.5394,      0.6015,
               -1.0495,      0.3520],
          [     1.2039,      0.5237,      1.1648,     -1.8082,      2.2170,
                0.1485,     -2.0055],
          [     0.5737,      0.0451,     -0.2114,     -1.1536,     -0.3056,
                1.3989,      0.7439],
          [     0.7367,     -1.3758,      0.1601,     -0.7796,      0.0368,
               -0.1972,     -1.2229],
          [    -0.1542,      0.7413,      0.2002,     -0.7236,      0.1040,
               -0.3299,      0.3296]],

         [[    -0.2768,     -0.6087,     -0.1098,      1.5755,      1.9923,
                0.4915,      0.9326],
          [    -0.0674,      0.1990,      0.0436,     -0.4586,     -0.8701,
                0.7301,     -0.6815],
          [    -0.1024,      0.6912,     -0.6503,      0.6281,      0.2793,
                0.7505,      0.5759],
          [    -0.3990,     -1.5420,      0.3596,     -0.8742,      0.1884,
          

tensor([[[[    0.0000,     0.0000,     0.4843,     0.0000,     0.6015,
               0.0000,     0.3520],
          [    1.2039,     0.5237,     1.1648,     0.0000,     2.2170,
               0.1485,     0.0000],
          [    0.5737,     0.0451,     0.0000,     0.0000,     0.0000,
               1.3989,     0.7439],
          [    0.7367,     0.0000,     0.1601,     0.0000,     0.0368,
               0.0000,     0.0000],
          [    0.0000,     0.7413,     0.2002,     0.0000,     0.1040,
               0.0000,     0.3296]],

         [[    0.0000,     0.0000,     0.0000,     1.5755,     1.9923,
               0.4915,     0.9326],
          [    0.0000,     0.1990,     0.0436,     0.0000,     0.0000,
               0.7301,     0.0000],
          [    0.0000,     0.6912,     0.0000,     0.6281,     0.2793,
               0.7505,     0.5759],
          [    0.0000,     0.0000,     0.3596,     0.0000,     0.1884,
               0.0000,     0.0000],
          [    0.0000,     0.0000, 

tensor([[[[    -0.0984,     -0.1231,      0.8939,     -0.2716,     -0.0230,
                0.1259,     -0.1429],
          [    -0.1216,      0.3227,     -0.0951,      0.4260,      0.9500,
                0.8642,      0.5017],
          [     1.0093,     -1.1650,      0.3158,     -0.0761,      0.0742,
                0.6339,      0.0338],
          [     0.6404,      0.7235,     -0.8119,     -0.7337,     -0.2155,
                0.1086,      0.6483],
          [     0.6719,      0.4549,      0.5288,      0.0816,     -0.2783,
               -0.2305,     -0.0269]],

         [[    -0.1536,     -0.1030,     -0.1574,     -0.0685,     -0.2933,
               -0.2222,      0.2986],
          [     0.4273,     -0.2709,     -0.2779,      0.6404,     -0.6782,
               -0.2934,     -0.2712],
          [     0.4125,      0.7818,     -1.2189,      0.5392,     -0.9057,
               -0.7793,      0.7066],
          [     0.5365,      0.7377,      0.1184,      0.3819,     -0.4482,
          

In [5]:
print(f'\nLINEAR')
for name, parameter in linear.named_parameters():
    print(name)
    print(parameter.shape, '\n')

print(f'\nCONV')
for name, parameter in conv2d.named_parameters():
    print(name)
    print(parameter.shape, '\n')

print(f'\nRELU')
for name, parameter in relu.named_parameters():
    print(name)
    print(parameter.shape, '\n')


LINEAR
weight
torch.Size([10, 4096]) 

bias
torch.Size([10]) 


CONV
weight
torch.Size([6, 3, 3, 3]) 

bias
torch.Size([6]) 


RELU
